import pandas as pd
import numpy as np
import subprocess
import os

def generate_table():
    print("Loading MATLAB output...")
    
    # Load the 1x8 arrays generated by MATLAB
    try:
        acm = np.genfromtxt('results_acm_original.csv', delimiter=',')
        go = np.genfromtxt('results_go_ipums.csv', delimiter=',')
    except FileNotFoundError:
        print("Error: Could not find CSV files. Run run_my_data.m first!")
        return

    # Structure the table data
    data = {
        'Parameter': [
            'Shock Dispersion ($\\nu$)', 
            '\\quad\\textit{t-statistic}',
            'Moving Cost ($C$)',
            '\\quad\\textit{t-statistic}',
            '\\midrule Shock Dispersion ($\\nu$)',
            '\\quad\\textit{t-statistic}',
            'Moving Cost ($C$)',
            '\\quad\\textit{t-statistic}'
        ],
        'Discount Factor ($\\beta$)': [
            '0.97 (Baseline)', '', '', '',
            '0.90 (Robustness)', '', '', ''
        ],
        'ACM (2010) Original': [
            f"{acm[0]:.2f}", f"({acm[1]:.2f})", 
            f"{acm[2]:.2f}", f"({acm[3]:.2f})",
            f"{acm[4]:.2f}", f"({acm[5]:.2f})", 
            f"{acm[6]:.2f}", f"({acm[7]:.2f})"
        ],
        'Lyn \\& Farrag (IPUMS)': [
            f"{go[0]:.2f}", f"({go[1]:.2f})", 
            f"{go[2]:.2f}", f"({go[3]:.2f})",
            f"{go[4]:.2f}", f"({go[5]:.2f})", 
            f"{go[6]:.2f}", f"({go[7]:.2f})"
        ]
    }

    df = pd.DataFrame(data)
    
    # Generate the LaTeX Code (Booktabs style for professional tables)
    latex_tabular = df.to_latex(index=False, escape=False, column_format='llcc')
    
    # --- UPGRADE 1: STANDALONE LATEX DOCUMENT ---
    latex_document = f"""\\documentclass[11pt]{{article}}
\\usepackage[margin=1in]{{geometry}}
\\usepackage{{booktabs}}
\\usepackage{{caption}}

\\begin{{document}}

\\begin{{table}}[htbp]
\\centering
\\caption{{Structural Estimation Replication (1975-2000; 1978--2003)}}
\\label{{tab:acm_replication}}
{latex_tabular}
\\vspace{{1ex}}
\\raggedright
\\footnotesize
\\textbf{{Notes and Methodological Differences:}} \\\\
(1) \\textbf{{Time Period:}} Both estimations cover a 26-year panel corresponding, with ACM covering 1975-2000 and Lyn & Farrag covering 1978-2003. \\\\
(2) \\textbf{{Linking \\& Matching:}} ACM (2010) utilizes a custom demographic linking algorithm to force matches across the 1995 CPS redesign. Lyn \\& Farrag rely on the modern IPUMS deterministic \\texttt{{cpsidp}} identifier. To maintain a continuous $T=26$ matrix for the GMM lag instruments, the IPUMS pipeline smooths transition holes caused by the 1985 and 1995 CPS sample redesigns via linear interpolation. \\\\
(3) \\textbf{{Real Wages \\& Composition Adjustment:}} ACM (2010) deflates raw survey income using a custom historical CPI file and computes composition-adjusted `Standard Worker' wages via matrix multiplication internal to the MATLAB engine. Lyn \\& Farrag deflate \\texttt{{incwage}} using the IPUMS-standardized \\texttt{{cpi99}} index and compute the pure sectoral wage index natively in Stata via the \\texttt{{margins}} command, passing fully finalized matrices to MATLAB.
\\end{{table}}

\\end{{document}}
"""

    # Save to a .tex file
    tex_filename = 'table_1_replication.tex'
    with open(tex_filename, 'w') as f:
        f.write(latex_document)
    print(f">>> SUCCESS: '{tex_filename}' generated.")

    # --- UPGRADE 2: COMPILE TO PDF VIA SUBPROCESS ---
    print(">>> Compiling LaTeX to PDF...")
    try:
        # Run pdflatex. We suppress the massive terminal output to keep it clean.
        result = subprocess.run(
            ['pdflatex', '-interaction=nonstopmode', tex_filename], 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE,
            text=True
        )
        
        if result.returncode == 0:
            print(">>> SUCCESS: 'table_1_replication.pdf' has been created!")
            
            # Optional Cleanup: Remove the junk files LaTeX generates
            for ext in ['.aux', '.log']:
                cleanup_file = tex_filename.replace('.tex', ext)
                if os.path.exists(cleanup_file):
                    os.remove(cleanup_file)
        else:
            print(">>> ERROR: pdflatex failed. Check the LaTeX syntax.")
            print(result.stdout) # Print the LaTeX error log
            
    except FileNotFoundError:
        print(">>> WARNING: 'pdflatex' command not found on this system.")
        print(">>> The .tex file was created, but you will need to compile it manually or install TeX Live on your server.")

if __name__ == "__main__":
    generate_table()