import pandas as pd
import numpy as np
import subprocess
import os

# Get the exact folder where this Python script lives
script_dir = os.path.dirname(os.path.abspath(__file__))
# Force Python to make this the active directory
os.chdir(script_dir)

PROJECT_ROOT = "/if/research-eme/omar/Gary/mobility_project"
RESULTS_ROOT = f"{PROJECT_ROOT}/output/acm_replication"
OUTPUT_DIR = f"{PROJECT_ROOT}/output/tables/heterogenous_workers_asec"

def generate_table():
    print(">>> Loading MATLAB output CSVs...")
    
    # Load all 8 arrays generated by MATLAB
    try:
        acm = np.genfromtxt(f'{RESULTS_ROOT}/results_acm_original.csv', delimiter=',')
        all_ipums = np.genfromtxt(f'{RESULTS_ROOT}/results_go_all.csv', delimiter=',')
        male = np.genfromtxt(f'{RESULTS_ROOT}/results_go_male.csv', delimiter=',')
        female = np.genfromtxt(f'{RESULTS_ROOT}/results_go_female.csv', delimiter=',')
        nocollege = np.genfromtxt(f'{RESULTS_ROOT}/results_go_nocollege.csv', delimiter=',')
        college = np.genfromtxt(f'{RESULTS_ROOT}/results_go_college.csv', delimiter=',')
        bluecollar = np.genfromtxt(f'{RESULTS_ROOT}/results_go_bluecollar.csv', delimiter=',')
        whitecollar = np.genfromtxt(f'{RESULTS_ROOT}/results_go_whitecollar.csv', delimiter=',')
    except FileNotFoundError as e:
        print(f">>> ERROR: Could not find one or more CSV files. {e}")
        return

    # Helper functions to format values to 2 decimal places
    def fmt(arr, idx): return f"{arr[idx]:.2f}"
    def fmt_t(arr, idx): return f"({arr[idx]:.2f})"

    # Helper function to build a complete column for a specific model
    def build_col(arr):
        return [
            '', # Empty row for Panel A header
            fmt(arr, 0), fmt_t(arr, 1), # Beta 0.97: Nu and t-stat
            fmt(arr, 2), fmt_t(arr, 3), # Beta 0.97: C and t-stat
            '', # Empty row for Panel B header
            fmt(arr, 4), fmt_t(arr, 5), # Beta 0.90: Nu and t-stat
            fmt(arr, 6), fmt_t(arr, 7)  # Beta 0.90: C and t-stat
        ]

    # Structure the table data
    data = {
        'Parameter': [
            '\\textbf{\\textit{Panel A: $\\beta = 0.97$}}',
            'Shock Dispersion ($\\nu$)', 
            '\\quad\\textit{t-statistic}',
            'Moving Cost ($C$)',
            '\\quad\\textit{t-statistic}',
            '\\midrule \\textbf{\\textit{Panel B: $\\beta = 0.90$}}',
            'Shock Dispersion ($\\nu$)',
            '\\quad\\textit{t-statistic}',
            'Moving Cost ($C$)',
            '\\quad\\textit{t-statistic}'
        ],
        'ACM (2010)': build_col(acm),
        'All (IPUMS)': build_col(all_ipums),
        'Male': build_col(male),
        'Female': build_col(female),
        'No College': build_col(nocollege),
        'College': build_col(college),
        'Blue Collar': build_col(bluecollar),
        'White Collar': build_col(whitecollar)
    }

    df = pd.DataFrame(data)
    
    # 1. Print a cleaned-up ASCII version to the Terminal
    df_print = df.copy()
    # Strip LaTeX formatting tags for a cleaner terminal view
    for tag in ['\\textbf', '\\textit', '\\quad', '\\midrule', '{', '}', '$']:
        df_print['Parameter'] = df_print['Parameter'].str.replace(tag, '', regex=False)
    df_print['Parameter'] = df_print['Parameter'].str.replace('\\nu', 'v', regex=False).str.replace('\\beta', 'Beta', regex=False)
    
    print("\n" + "="*120)
    print("TABLE 1: STRUCTURAL ESTIMATION REPLICATION AND SUB-GROUP HETEROGENEITY (1978-2003)")
    print("="*120)
    print(df_print.to_string(index=False))
    print("="*120 + "\n")

    # 2. Generate the LaTeX Code
    # lcccccccc = 1 left-aligned column for parameters, 8 center-aligned columns for data
    latex_tabular = df.to_latex(index=False, escape=False, column_format='lcccccccc')
    
    # Wrap the tabular environment in a resizebox so it fits perfectly on a PDF page
    latex_tabular = "\\resizebox{\\textwidth}{!}{%\n" + latex_tabular + "}"

    # 3. Create the Standalone LaTeX Document
    latex_document = f"""\\documentclass[11pt]{{article}}
\\usepackage[margin=1in]{{geometry}}
\\usepackage{{booktabs}}
\\usepackage{{caption}}
\\usepackage{{graphicx}} % Required for \\resizebox

\\begin{{document}}

\\begin{{table}}[htbp]
\\centering
\\caption{{Structural Estimation Replication and Sub-Group Heterogeneity (1978--2003)}}
\\label{{tab:acm_heterogeneity}}
{latex_tabular}
\\vspace{{1ex}}
\\raggedright
\\footnotesize
\\textbf{{Notes and Methodological Differences:}} \\\\
(1) \\textbf{{Time Period:}} All estimations cover a 26-year panel corresponding to survey years 1976--2001 (representing calendar years 1975--2000). \\\\
(2) \\textbf{{Linking \\& Matching:}} ACM (2010) utilizes a custom demographic linking algorithm to force matches across the 1995 CPS redesign. Farrag \\& Lyn rely on the modern IPUMS deterministic \\texttt{{cpsidp}} identifier. To maintain a continuous $T=26$ matrix, the IPUMS pipeline smooths transition holes caused by the 1985 and 1995 CPS sample redesigns via linear interpolation. \\\\
(3) \\textbf{{Real Wages \\& Sub-Groups:}} ACM (2010) deflates raw survey income using a custom historical CPI file and computes composition-adjusted `Standard Worker' wages via matrix multiplication internal to the MATLAB engine. Farrag \\& Lyn deflate \\texttt{{incwage}} using the IPUMS-standardized \\texttt{{cpi99}} index and compute the pure sectoral wage index natively in Stata via the \\texttt{{margins}} command. Sub-group columns represent separate estimations on completely stratified transition and wage matrices.
\\end{{table}}

\\end{{document}}
"""

    # 4. Save and Compile
    tex_filename = os.path.join(OUTPUT_DIR,'table_1_heterogeneity.tex')
    with open(tex_filename, 'w') as f:
        f.write(latex_document)
    print(f">>> SUCCESS: '{tex_filename}' generated.")

    print(">>> Compiling LaTeX to PDF...")
    try:
        os.chdir(OUTPUT_DIR)
        result = subprocess.run(
            ['pdflatex', '-interaction=nonstopmode', tex_filename], 
            stdout=subprocess.PIPE, 
            stderr=subprocess.PIPE,
            text=True
        )
        if result.returncode == 0:
            print(">>> SUCCESS: 'table_1_heterogeneity.pdf' has been created!")
            for ext in ['.aux', '.log']:
                cleanup_file = tex_filename.replace('.tex', ext)
                if os.path.exists(cleanup_file):
                    os.remove(cleanup_file)
        else:
            print(">>> ERROR: pdflatex failed. Check the LaTeX syntax.")
            print(result.stdout)
    except FileNotFoundError:
        print(">>> WARNING: 'pdflatex' command not found on this system.")

if __name__ == "__main__":
    generate_table()